import SwiftUI
import UIKit
import PlumeShared

/// The container app.
///
/// Unlike the keyboard extension there is no memory ceiling here, so the settings screens are the
/// shared Compose Multiplatform ones — the same code Android and the desktop render.
@main
struct PlumeApp: App {
    var body: some Scene {
        WindowGroup {
            RootView().ignoresSafeArea(.all)
        }
    }
}

/// Hosts the Compose settings UI. `MainViewControllerKt` is generated by Kotlin/Native from
/// `MainViewController` in iosMain.
struct ComposeSettings: UIViewControllerRepresentable {
    func makeUIViewController(context: Context) -> UIViewController {
        MainViewControllerKt.mainViewController()
    }

    func updateUIViewController(_ controller: UIViewController, context: Context) {}
}

/// The walkthrough comes first until the keyboard is usable, because everything in settings is
/// pointless while the keyboard cannot be reached.
struct RootView: View {
    var body: some View {
        ComposeSettings()
    }
}

/// Enabling a keyboard on iOS takes two separate steps in Settings, and the second one — Full
/// Access — is the one people miss. Without it the extension has no network and every action fails
/// with what looks like a broken provider.
struct KeyboardSetupView: View {
    var body: some View {
        VStack(alignment: .leading, spacing: 16) {
            Text("Enable the Plume keyboard").font(.title2.weight(.semibold))

            Label(
                "Settings → General → Keyboard → Keyboards → Add New Keyboard → Plume",
                systemImage: "1.circle"
            )
            Label(
                "Tap Plume in that list and turn on Allow Full Access",
                systemImage: "2.circle"
            )
            Text(
                "Full Access is what lets Plume reach your AI provider and read copied text. "
                + "Without it the keyboard appears but every action fails."
            )
            .font(.footnote)
            .foregroundStyle(.secondary)

            Button("Open Settings") {
                if let url = URL(string: UIApplication.openSettingsURLString) {
                    UIApplication.shared.open(url)
                }
            }
            .buttonStyle(.borderedProminent)
        }
        .padding()
    }
}
