#ifndef PLUME_FFI_H
#define PLUME_FFI_H

#pragma once

/* Generated with cbindgen:0.29.4 */

/* Warning: This file is auto-generated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef void *plume_ClipboardHandle;

/**
 * Opaque pointer types for safe cross-FFI boundary object passing
 */
typedef void *plume_HotkeyManagerHandle;

/**
 * Hotkey callback function type
 * The callback receives the action string that was registered
 */
typedef void (*plume_HotkeyCallback)(const char*);

typedef void *plume_SimulatorHandle;

/**
 * Get the last error message
 * Returns: C string (must be freed with plume_free_string) or NULL if no error
 */
const char *plume_get_last_error(void);

/**
 * Free a string allocated by Rust
 * This must be called for all strings returned by Rust functions
 */
void plume_free_string(char *s);

plume_ClipboardHandle plume_clipboard_new(void);

char *plume_clipboard_get_text(plume_ClipboardHandle handle);

int plume_clipboard_set_text(plume_ClipboardHandle handle, const char *text);

int plume_clipboard_save(plume_ClipboardHandle handle);

int plume_clipboard_restore(plume_ClipboardHandle handle);

void plume_clipboard_free(plume_ClipboardHandle handle);

plume_HotkeyManagerHandle plume_hotkey_manager_new(void);

int plume_hotkey_clear(plume_HotkeyManagerHandle handle);

int plume_hotkey_register(plume_HotkeyManagerHandle handle,
                          const char *binding,
                          const char *action,
                          plume_HotkeyCallback callback);

int plume_hotkey_start(plume_HotkeyManagerHandle handle);

int plume_hotkey_stop(plume_HotkeyManagerHandle handle);

void plume_hotkey_manager_free(plume_HotkeyManagerHandle handle);

plume_SimulatorHandle plume_simulator_new(void);

int plume_simulate_select_all(plume_SimulatorHandle handle);

int plume_simulate_copy(plume_SimulatorHandle handle);

int plume_simulate_paste(plume_SimulatorHandle handle);

void plume_simulator_free(plume_SimulatorHandle handle);

#endif  /* PLUME_FFI_H */
