#ifndef PLUME_FFI_H
#define PLUME_FFI_H

#pragma once

/* Generated with cbindgen:0.29.4 */

/* Warning: This file is auto-generated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef void *plume_ClipboardHandle;

typedef void *plume_HotkeyManagerHandle;

/**
 * Receives the action string the binding was registered with.
 */
typedef void (*plume_HotkeyCallback)(const char*);

typedef void *plume_SimulatorHandle;

/**
 * NULL when there is no error; otherwise a string the caller must free with `plume_free_string`.
 */
const char *plume_get_last_error(void);

/**
 * Must be called for every string a Rust function returns.
 */
void plume_free_string(char *s);

plume_ClipboardHandle plume_clipboard_new(void);

/**
 * Null when the clipboard holds no text, including when it holds an image.
 */
char *plume_clipboard_get_text(plume_ClipboardHandle handle);

/**
 * 1 when the clipboard holds text, 0 when not. Distinguishes "copied a picture" from
 * "the copy never landed", which look identical through `get_text`.
 */
int plume_clipboard_has_text(plume_ClipboardHandle handle);

int plume_clipboard_set_text(plume_ClipboardHandle handle, const char *text);

/**
 * Empties the clipboard, so a following simulated copy landing becomes observable.
 */
int plume_clipboard_clear(plume_ClipboardHandle handle);

int plume_clipboard_save(plume_ClipboardHandle handle);

int plume_clipboard_restore(plume_ClipboardHandle handle);

void plume_clipboard_free(plume_ClipboardHandle handle);

plume_HotkeyManagerHandle plume_hotkey_manager_new(void);

int plume_hotkey_clear(plume_HotkeyManagerHandle handle);

int plume_hotkey_register(plume_HotkeyManagerHandle handle,
                          const char *binding,
                          const char *action,
                          plume_HotkeyCallback callback);

int plume_hotkey_start(plume_HotkeyManagerHandle handle);

int plume_hotkey_stop(plume_HotkeyManagerHandle handle);

void plume_hotkey_manager_free(plume_HotkeyManagerHandle handle);

plume_SimulatorHandle plume_simulator_new(void);

int plume_simulate_select_all(plume_SimulatorHandle handle);

int plume_simulate_copy(plume_SimulatorHandle handle);

int plume_simulate_paste(plume_SimulatorHandle handle);

/**
 * Releases modifiers still held from the triggering hotkey. Call once before any combo.
 */
int plume_simulate_release_modifiers(plume_SimulatorHandle handle);

void plume_simulator_free(plume_SimulatorHandle handle);

#endif  /* PLUME_FFI_H */
